### ISSUE TITLE
Incorrect formating with some articles

### ISSUE THREAD

**Issue by JustinHo97** [TravelAdvisory/Travel-Advisor#7]
for some reason, text is in p tags when element is created
[image](https://screenshots.firefox.com/MBN3E2AFf180V0nC/null)

**Comment by JustinHo97** [comment]
Issue caused by nyt api returning "topics" instead of just articles. We'll need to eventually find a way to just return articles

**Comment by tricialeav** [comment]
Fixed the formatting issue by revising the css file to target the dynamically created <p> tags. TODO look into article verification (return only articles). Will add to Trello.
